<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Pry.Core/Pry.Core.csproj" />
    <ProjectReference Include="../Pry.Contracts/Pry.Contracts.csproj" />
    <Content Include="../Pry.App/Resources/**" Link="Resources/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
