<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.20" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.20" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.20" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.20" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.94.2" />
    <ProjectReference Include="../Pry.Core/Pry.Core.csproj" />
    <AvaloniaResource Include="Assets/**" />
    <Content Include="Resources/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
